name: Java CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Установка Java
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Сборка с Maven
      run: mvn -B package --file pom.xml
    - name: Тестирование
      run: mvn -B test --file pom.xml
